let dishes = [
    {
        category : "burger_and_sandwiches_content",
        picture : "mushroom_burbur",
        name : "Veggie mushroom black burger",
        description : "Mixed green salad, Tomatoes, Edamame, Mushrooms",
        price : "16,90€",
    },
    {
        category : "burger_and_sandwiches_content",
        picture : "meat_burbur",
        name : "All meat burger",
        description : "Beef, Bacon, Dill pickles, Smoked cheese, Ketchup, BBQ souse",
        price : "15,90€",
    },
    {
        category : "burger_and_sandwiches_content",
        picture : "red_burbur",
        name : "Beef red burger",
        description : "Beef, Cheese, Tomatoes, Lettuce, Onion",
        price : "14,90€",
    },
    {
        category : "burger_and_sandwiches_content",
        picture : "chicken_burbur",
        name : "BIg chicken burger",
        description : "Chicken, Cheese, Tomatoes, Lettuce, Onion, Bell pepper, ",
        price : "15,90€",
    },
    {
        category : "pizza_content",
        picture : "margherita_pizza",
        name : "Pizza Margherita",
        description : "Tomato Sauce, Mozzarella",
        price : "11,90€",
    },
    {
        category : "pizza_content",
        picture : "chorizo_pizza",
        name : "Pizza Chorizo",
        description : "Tomato slices, Mozzarella, Chorizo",
        price : "13,90€",
    },
    {
        category : "pizza_content",
        picture : "funghi_pizza",
        name : "Funghi",
        description : "Red onion, Olives, Button Mushrooms, Mozzarella",
        price : "12,90€",
    },
    {
        category : "pizza_content",
        picture : "formaggi_pizza",
        name : "Quattro Formaggi with Chicken ",
        description : "Chicken, Mozzarella, Gorgonzola, Fontina,  Parmigiano Reggiano",
        price : "15,90€",
    },
    {
        category : "salad_content",
        picture : "arugular_salad",
        name : "Warm beef arugula salad",
        description : "Beef, Arugula, Field salad, Greek feta, Cherry tomatoes, Sun-dried Tomatoes, Balsamic-vinegar dressing",
        price : "16,90€",
    },
    {
        category : "salad_content",
        picture : "mini_salad",
        name : "Mini green Salad",
        description : "Green salad, Cucumber, Carrots, Parsley, Radishes ",
        price : "7,90€",
    },
    {
        category : "salad_content",
        picture : "sea_food_salad",
        name : "Green Salad with sea food",
        description : "Mixed greens, Cherry tomatoes, Red onion, Mussels, Squid rings, Shrimp, Dijon mustard-lemon dressing with dill",
        price : "16,90€",
    },
    {
        category : "salad_content",
        picture : "vegan_salad",
        name : "Vegan green salad with tofu",
        description : "Green salad, Cherry tomatoes, Cucumber, Baby spinach, Edamame, Radishes, Bittercress, Tofu, Peanuts",
        price : "14,90€",
    },
];